<a href="https://colab.research.google.com/github/architawasthi99/Pandas/blob/main/01_pandas_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Series** **from** **List**

In [1]:
import numpy as np
import pandas as pd

In [5]:
#string
country=['india','usa','russia','china','aghanistan']
pd.Series(country)

0         india
1           usa
2        russia
3         china
4    aghanistan
dtype: object

In [6]:
#integer
runs=[54,2,100,99,45]
pd.Series(runs)

0     54
1      2
2    100
3     99
4     45
dtype: int64

In [7]:
#custom index

marks=[10,20,30,40,50]
subjects=['hindi','english','physics','chemistry','history']
pd.Series(marks,index=subjects)

hindi        10
english      20
physics      30
chemistry    40
history      50
dtype: int64

In [8]:
#setting a name to series object
pd.Series(marks,index=subjects,name='archit marks')

hindi        10
english      20
physics      30
chemistry    40
history      50
Name: archit marks, dtype: int64

**Series** **using** **dict**

In [11]:
marks={
    'hindi':29,
    'english':100,
    'maths':99
}
new_marks=pd.Series(marks,name='archit hua pass')
new_marks

hindi       29
english    100
maths       99
Name: archit hua pass, dtype: int64