<a href="https://colab.research.google.com/github/architawasthi99/Pandas/blob/main/02_pandas_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Series** **from** **List**

In [13]:
import numpy as np
import pandas as pd

In [14]:
#string
country=['india','usa','russia','china','aghanistan']
pd.Series(country)

0         india
1           usa
2        russia
3         china
4    aghanistan
dtype: object

In [15]:
#integer
runs=[54,2,100,99,45]
pd.Series(runs)

0     54
1      2
2    100
3     99
4     45
dtype: int64

In [16]:
#custom index

marks=[10,20,30,40,50]
subjects=['hindi','english','physics','chemistry','history']
pd.Series(marks,index=subjects)

hindi        10
english      20
physics      30
chemistry    40
history      50
dtype: int64

In [17]:
#setting a name to series object
marks_series=pd.Series(marks,index=subjects,name='archit marks')
marks_series

hindi        10
english      20
physics      30
chemistry    40
history      50
Name: archit marks, dtype: int64

**Series** **using** **dict**

In [18]:
marks={
    'hindi':29,
    'english':100,
    'maths':99
}
new_marks=pd.Series(marks,name='archit hua pass')
new_marks

hindi       29
english    100
maths       99
Name: archit hua pass, dtype: int64

**Series** **attributes**

In [19]:
#size
marks_series.size

5

In [20]:
#dtype
marks_series.dtype

dtype('int64')

In [21]:
#is_unique
marks_series.is_unique

True

In [22]:
#index
marks_series.index

Index(['hindi', 'english', 'physics', 'chemistry', 'history'], dtype='object')

In [23]:
#values
marks_series.values

array([10, 20, 30, 40, 50])

**SERIES** **USING** **read_csv**

In [24]:
#with 1 column
print(type(pd.read_csv('/content/subs.csv').squeeze("columns")))

subs=pd.read_csv('/content/subs.csv').squeeze("columns")
subs

<class 'pandas.core.series.Series'>

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [25]:
#with 2 column
vk=pd.read_csv('/content/kohli_ipl.csv',index_col='match_no').squeeze("columns")
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [26]:
movies=pd.read_csv('/content/bollywood.csv',index_col='movie').squeeze("columns")
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

**SERIES** **METHODS**

In [27]:
# head and tail

vk.head()

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [28]:
vk.head(2)

match_no
1     1
2    23
Name: runs, dtype: int64

In [29]:
vk.tail()

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [30]:
vk.tail(2)

match_no
214    25
215     7
Name: runs, dtype: int64

In [31]:
#sample
movies.sample(10)

movie
Black (2005 film)                   Amitabh Bachchan
Raaz: Reboot                           Emraan Hashmi
Jodhaa Akbar                          Hrithik Roshan
Rustom (film)                          Ileana D'Cruz
Flavors (film)                            Reef Karim
Raman Raghav 2.0                 Nawazuddin Siddiqui
Dum Laga Ke Haisha                Ayushmann Khurrana
Uvaa                                    Mohit Baghel
Beyond the Clouds (2017 film)         Ishaan Khattar
Run (2004 film)                    Abhishek Bachchan
Name: lead, dtype: object

In [32]:
#value_counts
movies.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [33]:
#sort_values
print(vk.sort_values(ascending=False).head(3).values[0])
print(vk.sort_values(ascending=False).head(3).values[1])

113
109

In [34]:
vk.sort_values()

match_no
8        0
87       0
93       0
91       0
206      0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [35]:
#sort_index
movies.sort_index()

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: object

**series** **maths** **methods**

In [36]:
#count
print(vk.count())

215

In [37]:
# sum and product
print(subs.sum())

print(subs.product())

49510
0

In [38]:
# mean -> median -> mod -> std -> var
print(subs.mean())

135.64383561643837

In [41]:
print(vk.median())

24.0

In [43]:
print(movies.mode())

0    Akshay Kumar
Name: lead, dtype: object

In [44]:
print(subs.std())

62.67502303725269

In [45]:
print(vk.var())

688.0024777222344

In [47]:
# min and max
print(subs.min())

print(subs.max())

33
396

In [48]:
#describe
vk.describe()

count    215.000000
mean      30.855814
std       26.229801
min        0.000000
25%        9.000000
50%       24.000000
75%       48.000000
max      113.000000
Name: runs, dtype: float64

**SERIES** **INDEXING**

In [49]:
#integer indexing
x=pd.Series([12,5,656,23,97,6,3,99,100])
print(x[4])

97

In [53]:
#slicing
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [52]:
vk[5:16]

match_no
6      9
7     34
8      0
9     21
10     3
11    10
12    38
13     3
14    11
15    50
16     2
Name: runs, dtype: int64

In [54]:
vk[-5:]

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [55]:
movies[-5:]

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [56]:
movies[::2]

movie
Uri: The Surgical Strike                   Vicky Kaushal
The Accidental Prime Minister (film)         Anupam Kher
Evening Shadows                         Mona Ambegaonkar
Fraud Saiyaan                               Arshad Warsi
Manikarnika: The Queen of Jhansi          Kangana Ranaut
                                              ...
Raaz (2002 film)                              Dino Morea
Waisa Bhi Hota Hai Part II                  Arshad Warsi
Kaante                                  Amitabh Bachchan
Aankhen (2002 film)                     Amitabh Bachchan
Company (film)                                Ajay Devgn
Name: lead, Length: 750, dtype: object

In [57]:
# FANCY INDEXING
vk[[1,3,4,5]]

match_no
1     1
3    13
4    12
5     1
Name: runs, dtype: int64

In [58]:
#label indexing
movies['Raaz (2002 film)']

'Dino Morea'

**EDITING** **SERIES**

In [61]:
#using index
marks_series[1]=100
marks_series

/tmp/ipykernel_535/4083200148.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks_series[1]=100

hindi         10
english      100
physics       30
chemistry     40
history       50
Name: archit marks, dtype: int64

In [63]:
#without index
marks_series['sst']=300
marks_series

hindi         10
english      100
physics       30
chemistry     40
history       50
sst          300
Name: archit marks, dtype: int64