<a href="https://colab.research.google.com/github/architawasthi99/Pandas/blob/main/05_series_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
subs=pd.read_csv('/content/subs.csv').squeeze("columns")
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [38]:
movies=pd.read_csv('/content/bollywood.csv',index_col='movie').squeeze("columns")
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [12]:
vk=pd.read_csv('/content/kohli_ipl.csv',index_col='match_no').squeeze("columns")
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [7]:
#astype
import sys
sys.getsizeof(vk)

3604

In [8]:
sys.getsizeof(vk.astype('int16'))

1024

In [16]:
#between
vk[vk.between(51,99)].size

43

In [17]:
#clip
vk.clip(100,200)

match_no
1      100
2      100
3      100
4      100
5      100
      ...
211    100
212    100
213    100
214    100
215    100
Name: runs, Length: 215, dtype: int64

In [18]:
temp=pd.Series([1,1,2,2,3,3,4,4,5,5])
temp

0    1
1    1
2    2
3    2
4    3
5    3
6    4
7    4
8    5
9    5
dtype: int64

In [19]:
temp.drop_duplicates()

0    1
2    2
4    3
6    4
8    5
dtype: int64

In [21]:
temp.duplicated().sum()

np.int64(5)

In [22]:
temp=pd.Series([22,21,54,np.nan,1,np.nan,99])
temp

0    22.0
1    21.0
2    54.0
3     NaN
4     1.0
5     NaN
6    99.0
dtype: float64

In [24]:
temp.size

7

In [26]:
temp.count()

np.int64(5)

In [28]:
temp[temp.isnull()]

3   NaN
5   NaN
dtype: float64

In [29]:
#dropna
temp.dropna()

0    22.0
1    21.0
2    54.0
4     1.0
6    99.0
dtype: float64

In [31]:
#fillna
temp.fillna(111)

0     22.0
1     21.0
2     54.0
3    111.0
4      1.0
5    111.0
6     99.0
dtype: float64

In [34]:
#isin
vk[(vk==49) | (vk==99)]

match_no
82    99
86    49
Name: runs, dtype: int64

In [36]:
vk[vk.isin([49,99])]

match_no
82    99
86    49
Name: runs, dtype: int64

In [43]:
#apply
movies.apply(lambda x:x.split()[0].upper()).head(3)

movie
Uri: The Surgical Strike                 VICKY
Battalion 609                            VICKY
The Accidental Prime Minister (film)    ANUPAM
Name: lead, dtype: object

In [45]:
marks=pd.Series([10,20,30,40])
marks.apply(lambda x:x+500)

0    510
1    520
2    530
3    540
dtype: int64

In [46]:
def result(marks):
  if marks>50:
    return 'pass'
  else:
    return 'fail'
marks=pd.Series([65,87,32,35,90])

print(marks.apply(result))

0    pass
1    pass
2    fail
3    fail
4    pass
dtype: object

In [ ]:
#copy